# Generated by Django 5.2.1 on 2025-05-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=100, verbose_name='tipo de incidente')),
                ('description', models.TextField(verbose_name='descripción')),
                ('date', models.DateField(verbose_name='fecha del incidente')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comentario de solución')),
                ('status', models.CharField(choices=[('activo', 'Incidente Activo'), ('resuelto', 'Incidente Resuelto')], default='activo', max_length=20, verbose_name='estado del incidente')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='modificado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'db_table': 'incident',
            },
        ),
    ]
