# Generated by Django 5.2.1 on 2025-05-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.CharField(max_length=50, verbose_name='fecha del incidente'),
        ),
    ]
