# Generated by Django 5.2.1 on 2025-06-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_alter_incident_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(verbose_name='descripción'),
        ),
    ]
